export default {
  activeUser: {},
  event: {},
  eventsDetails: {
    events: [],
    pageInfo: {},
  },
  subscribedEvents: [],
  redirectUrl: '',
  interest: {},
  interests: {},
  attendees: {},
  attendee: {},
  joinedCategories: {},
  socialClubs: {},
  socialClub: {},
  eventsSearchList: [],
  oauth: '',
  invite: {},
};
